# feature extraction

In [30]:
import cv2

In [31]:
import os
from tqdm import tqdm #to show process bar

In [48]:
train='C://Users/shash/Desktop/train'
predict='C://Users/shash/Desktop/test1'

In [33]:
n='cat.1.jpg'
n.split('.')[0]

'cat'

In [34]:
def label_img(img):
    label=img.split('.')
    if label[0]=='cat':
        return 0
    elif label[0]=='dog':
        return 1

In [35]:
for i in n:
    r=label_img(i)
    print(r)

None
None
None
None
None
None
None
None
None


In [36]:
from random import shuffle
train_data=[]
def feature_data():
    for i in tqdm(os.listdir(train)):
        label=label_img(i)
        path=os.path.join(train,i) #train/cat.01.jpg etc.
        feature=cv2.imread(path,0) #extract features or pixels(mathematical value of image)
        feature=cv2.resize(feature,(50,50)) #converting all images to same size
        train_data.append([[feature],[label]]) 
    shuffle(train_data)
    return train_data

In [37]:
training=feature_data()

100%|████████████████████████████████████████████████████████████████████████████| 25000/25000 [06:13<00:00, 66.87it/s]


In [49]:
from random import shuffle
test_data=[]
def testing_data():
    for i in tqdm(os.listdir(predict)):
        label=label_img(i)
        path=os.path.join(predict,i) #train/cat.01.jpg etc.
        feature=cv2.imread(path,0) #extract features or pixels
        feature=cv2.resize(feature,(50,50)) #converting all images to same size
        test_data.append([[feature],[label]]) 
    shuffle(test_data)
    return test_data

In [50]:
testing=testing_data()

100%|████████████████████████████████████████████████████████████████████████████| 12500/12500 [04:38<00:00, 44.92it/s]


In [51]:
import numpy as np
training=np.array(training).reshape(25000,2)
training.shape

(25000, 2)

In [52]:
training

array([[array([[105,  96, 123, ...,  90, 106, 131],
       [115, 117,  81, ..., 119, 114, 131],
       [129, 140,  92, ..., 119, 122, 130],
       ...,
       [163, 123, 123, ..., 193, 194, 196],
       [146, 163, 145, ..., 191, 193, 193],
       [124, 170, 143, ..., 210, 192, 191]], dtype=uint8),
        0],
       [array([[ 15,  36,  42, ..., 135,  55,  58],
       [ 24,  23,  37, ...,  73,  59,  58],
       [ 26,  29,  34, ..., 138, 115, 106],
       ...,
       [195, 192, 209, ..., 129,  83, 150],
       [188, 207, 209, ..., 139,  76, 170],
       [191, 205, 187, ..., 175, 173, 178]], dtype=uint8),
        1],
       [array([[103, 105, 115, ...,  80, 110,  97],
       [102, 101, 102, ...,  90,  82, 107],
       [ 60,  59,  63, ...,  86,  77,  78],
       ...,
       [178, 168, 167, ..., 182, 181, 177],
       [176, 171, 173, ..., 186, 183, 181],
       [176, 172, 171, ..., 153, 146, 135]], dtype=uint8),
        1],
       ...,
       [array([[142, 141, 143, ..., 117, 114, 116],
   

In [55]:
z=np.array([[[2,3,4,5],[1]],[[3,6,2,5],[0]],[[3,6,2,5],[0]]]) #example

In [56]:
z.shape #example

(3, 2)

In [2]:
import numpy as np
n=np.ones([3,5]) #created zero array so that we can replace with real value
n

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [3]:
z[0][0]

NameError: name 'z' is not defined

In [65]:
for i in range(3):
    n[i]=np.hstack((z[i][0],z[i][1]))     #same as axis=1  

In [66]:
n

array([[2., 3., 4., 5., 1.],
       [3., 6., 2., 5., 0.],
       [3., 6., 2., 5., 0.]])

In [ ]:
y=n[]

In [71]:
import numpy as np
z=np.zeros([25000,2501])

In [72]:
c=np.arange(20).reshape(4,5) #example

In [73]:
c.ravel() #to convert to single line #example

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [74]:
for i in range(25000):
    z[i]=np.hstack((training[i][0].ravel(),training[i][1]))

In [75]:
z
x=z[:,:-1]
y=z[:,-1:]

In [76]:
x.shape

(25000, 2500)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
knn=KNeighborsclassifier(n_neighbors=5)

In [ ]:
knn.fit(xtrain,ytrain)

In [ ]:
ypred=knn.predict(xtest)